# Logger options
log_iter: 5                 # How often to log the training loss 
val_iter: 10                # How often to validate testing and save output images during training

# Optimization options
max_iter: 12000              # Maximum number of training iterations
batch_size: 1                 # Batch size
loss: simple_speckle
optimizer: Adam               # Optimizer for trainings
weight_decay: 0.0             # Weight decay
beta1: 0.9                    # Adam parameter
beta2: 0.999                  # Adam parameter
lr: 0.00001                    # Initial learning rate [RFF: 10-3, Neural Recon: 10-4, Prior-based Neural Recon: 10-5]

# Model options
model: SIREN                # Options for MLP models
net: 
  network_input_size: 128    # Input size for network
  network_output_size: 1
  network_depth: 3           # Depth of MLP layers
  network_width: 32        # Width of MLP layers

encoder:
  embedding: gauss           # Input embedding method
  scale: 0.5
  embedding_size: 64       # Embedding size for input Fourier feature encoding
  coordinates_size: 2

cutoff_idx: 3                # Low Pass Filter Cutoff


# Data
img_size: 32     # (92, 256, 256)
num_looks: 20     # Number of looks to use
